"""empty message

Revision ID: 556fc257566f
Revises: dc1714ab1265
Create Date: 2025-01-13 17:40:09.625270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556fc257566f'
down_revision = 'dc1714ab1265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
